services:
  store-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge
