export class CallbackRequestBodyDto {
  event: string;
  context: {
    id: number;
    source_uuid: string | null;
    global_source_uuid: string | null;
    status_on_source: string | null;
    source_id: number;
    client_id: number;
    grand_total: number;
    total_discount: number;
    margin_sum: number;
    expenses_sum: number;
    discount_amount: number | null;
    discount_percent: number | null;
    shipping_price: number | null;
    taxes: number | null;
    register_id: number | null;
    fiscal_result: any[];
    fiscal_status: string | null;
    shipping_type_id: number | null;
    manager_id: number;
    status_group_id: number;
    status_id: number;
    closed_from: string | null;
    status_expired_at: string | null;
    status_changed_at: string;
    parent_id: number | null;
    manager_comment: string | null;
    client_comment: string;
    discount_data: any[];
    is_gift: boolean;
    promocode: string | null;
    wrap_price: number | null;
    gift_wrap: boolean;
    payment_status: string;
    gift_message: string | null;
    last_synced_at: string | null;
    created_at: string;
    updated_at: string;
    closed_at: string | null;
    ordered_at: string;
    source_updated_at: string | null;
    deleted_at: string | null;
    payments_total: number;
    products_total: number;
    is_expired: boolean;
    has_reserves: boolean;
  };
}
